# Generated by Django 2.2.3 on 2019-07-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.IntegerField(verbose_name='room')),
                ('dues', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='dues')),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='rent')),
                ('electric_bill', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='electric_bill')),
                ('dob', models.DateTimeField(auto_now_add=True, verbose_name='dob')),
            ],
        ),
        migrations.CreateModel(
            name='consumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.IntegerField(verbose_name='room')),
                ('reading', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='reading')),
                ('dor', models.DateTimeField(auto_now_add=True, verbose_name='dor')),
            ],
        ),
        migrations.CreateModel(
            name='my_users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_user_name', models.CharField(max_length=100, verbose_name='name')),
                ('authority', models.IntegerField(default=0, verbose_name='authority')),
                ('my_user_pass', models.CharField(max_length=100, verbose_name='pass')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.IntegerField(verbose_name='room')),
                ('amount', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='amount')),
                ('dop', models.DateTimeField(auto_now_add=True, verbose_name='dop')),
            ],
        ),
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_room_no', models.DecimalField(decimal_places=0, max_digits=2, verbose_name='room_no')),
                ('user_name', models.CharField(max_length=100, verbose_name='name')),
                ('user_date_entry', models.IntegerField(default=0, verbose_name='date_entry')),
                ('user_doj', models.DateTimeField(verbose_name='doj')),
                ('user_contact', models.IntegerField(default=0, verbose_name='contact')),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='rent')),
                ('bill_prep', models.IntegerField(default=0, verbose_name='bill_prep')),
            ],
        ),
    ]
