# Generated by Django 2.2.3 on 2019-08-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.IntegerField(verbose_name='room')),
                ('payed', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='payed')),
                ('dues', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='dues')),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='rent')),
                ('previous_reading', models.DecimalField(decimal_places=2, default=1000000, max_digits=10, verbose_name='prev_read')),
                ('current_reading', models.DecimalField(decimal_places=2, default=1000000, max_digits=10, verbose_name='curr_read')),
                ('electric_bill', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='electric_bill')),
                ('dob', models.DateField(verbose_name='dob')),
            ],
        ),
        migrations.CreateModel(
            name='consumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.IntegerField(default=0, verbose_name='room')),
                ('reading', models.DecimalField(decimal_places=1, default=0.0, max_digits=10, verbose_name='reading')),
                ('dor', models.DateField(verbose_name='dor')),
            ],
        ),
        migrations.CreateModel(
            name='my_users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_user_name', models.CharField(max_length=100, verbose_name='name')),
                ('authority', models.IntegerField(default=0, verbose_name='authority')),
                ('my_user_pass', models.CharField(max_length=100, verbose_name='pass')),
            ],
        ),
        migrations.CreateModel(
            name='own_bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datee', models.DateField(verbose_name='datee')),
                ('reading', models.IntegerField(verbose_name='reading')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cost')),
                ('type', models.IntegerField(verbose_name='typee')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.IntegerField(verbose_name='room')),
                ('amount', models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='amount')),
                ('dop', models.DateTimeField(verbose_name='dop')),
            ],
        ),
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_room_no', models.DecimalField(decimal_places=0, default=0, max_digits=2, verbose_name='room_no')),
                ('user_name', models.CharField(max_length=100, verbose_name='name')),
                ('user_date_entry', models.IntegerField(default=0, verbose_name='date_entry')),
                ('user_doj', models.DateField(verbose_name='doj')),
                ('user_contact', models.IntegerField(default=0, verbose_name='contact')),
                ('user_rent', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='rent')),
                ('previous_units', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='prev_units')),
                ('previous_dues', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='prev_dues')),
                ('billed', models.IntegerField(default=0, verbose_name='billed')),
            ],
        ),
    ]
