# Generated by Django 2.2.3 on 2019-07-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='bill_prep',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='rent',
        ),
        migrations.AddField(
            model_name='user_details',
            name='billed',
            field=models.IntegerField(default=0, verbose_name='billed'),
        ),
        migrations.AddField(
            model_name='user_details',
            name='previous_dues',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='prev_dues'),
        ),
        migrations.AddField(
            model_name='user_details',
            name='previous_units',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='prev_units'),
        ),
        migrations.AddField(
            model_name='user_details',
            name='user_rent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='rent'),
        ),
        migrations.AlterField(
            model_name='consumption',
            name='dor',
            field=models.DateTimeField(verbose_name='dor'),
        ),
        migrations.AlterField(
            model_name='consumption',
            name='reading',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10, verbose_name='reading'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='user_doj',
            field=models.DateField(verbose_name='doj'),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='user_room_no',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2, verbose_name='room_no'),
        ),
    ]
