# Generated by Django 2.2.3 on 2019-08-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='own_bill',
            name='datee',
        ),
        migrations.AddField(
            model_name='own_bill',
            name='date',
            field=models.DateField( verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='own_bill',
            name='type',
            field=models.IntegerField(verbose_name='type'),
        ),
    ]
