# Generated by Django 2.2.3 on 2019-08-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190801_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='own_bill',
            name='date',
            field=models.DateField(default='0000-01-01', verbose_name='date'),
        ),
    ]
