# Generated by Django 2.2.3 on 2019-07-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190704_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='dob',
            field=models.DateField(auto_now_add=True, verbose_name='dob'),
        ),
        migrations.AlterField(
            model_name='consumption',
            name='dor',
            field=models.DateField(verbose_name='dor'),
        ),
    ]
