# Generated by Django 2.2.3 on 2019-08-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190801_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='own_bill',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
    ]
