# Generated by Django 2.2.3 on 2019-07-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190708_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='room_no',
            field=models.IntegerField(default=0, verbose_name='room'),
        ),
    ]
