# Generated by Django 2.2.3 on 2019-07-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190708_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='dor',
            field=models.DateField(verbose_name='dor'),
        ),
    ]
