# Generated by Django 2.2.3 on 2019-07-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190708_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='payed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='payed'),
            preserve_default=False,
        ),
    ]
