# Generated by Django 2.2.3 on 2019-07-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_bill_payed'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='payed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='payed'),
            preserve_default=False,
        ),
    ]
