# Generated by Django 2.2.3 on 2019-07-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_bill_payed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='dob',
            field=models.DateField(verbose_name='dob'),
        ),
    ]
